import type { CronConfig } from './schemas';

export const mockCronConfigs: CronConfig[] = [
    {
        id: '1',
        groupName: 'PJD SERVICIO Y EVENTOS',
        apiUrl: 'https://secure.parquejaimeduque.com/consulta-total-ventas.asp',
        apiLoginUrl: 'https://secure.parquejaimeduque.com/login.asp',
        timezone: 'America/Bogota',
        username: 'brad.moyetones',
        password: 'brad130403',
        hiddenField: 'S',
        startAt: '10:00',
        intervalMinutes: 30,
        isActive: true,
        createdAt: new Date('2024-01-15'),
        updatedAt: new Date('2024-12-09'),
    },
    {
        id: '2',
        groupName: 'PJD VENTAS',
        apiUrl: 'https://secure.parquejaimeduque.com/consulta-ventas.asp',
        apiLoginUrl: 'https://secure.parquejaimeduque.com/login.asp',
        timezone: 'America/Bogota',
        username: 'admin.ventas',
        password: 'secure123456',
        hiddenField: 'S',
        startAt: '08:00',
        intervalMinutes: 60,
        isActive: false,
        createdAt: new Date('2024-02-01'),
        updatedAt: new Date('2024-12-08'),
    },
    {
        id: '3',
        groupName: 'PJD REPORTES',
        apiUrl: 'https://secure.parquejaimeduque.com/consulta-reportes.asp',
        apiLoginUrl: 'https://secure.parquejaimeduque.com/login.asp',
        timezone: 'America/Bogota',
        username: 'reportes.admin',
        password: 'report999777',
        hiddenField: 'S',
        startAt: '06:00',
        intervalMinutes: 120,
        isActive: true,
        createdAt: new Date('2024-03-10'),
        updatedAt: new Date('2024-12-07'),
    },
];
